name: compliance_tablet
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.5
  google_fonts: 6.1.0
  bloc: ^8.1.4
  flutter_screenutil: ^5.9.0
  ionicons: ^0.2.2
  font_awesome_flutter: ^10.7.0
  sidebarx: ^0.16.3
  syncfusion_flutter_charts: ^25.1.38
  percent_indicator: ^4.0.1
  pin_code_fields: ^8.0.1
  lottie: ^3.1.0
  equatable: ^2.0.5
  syncfusion_flutter_datagrid: ^25.1.39
  pocketbase: ^0.18.1
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  path_provider: ^2.1.2

dev_dependencies:
  hive_generator :
  build_runner: ^2.4.8
  build_test: ^2.2.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottify/
